### PR TITLE
Add instruction for hiding native tabs

### PR DESCRIPTION
**Pull request by MasterKia**
https://superuser.com/questions/1424478/can-i-hide-native-tabs-at-the-top-of-firefox

Partially addresses https://github.com/asamuzaK/sidebarTabs/issues/5.

### CODE REVIEW

**Comment by asamuzaK** [comment]
I do not agree with adding this explanation.
* The extension does not completely replace the native tab bar, for example,  it does not support some context menu items.
* There is no easy way to restore the native tab bar.
  If you close the sidebar or load something other than this extension into the sidebar, you will have no way to access the tabs.
* If someone is aware of those above and still want to hide the tab bar, I am sure that they will search and find a solution themselves. Just like you did this time:-)
  So this kind of explanation is unnecessary anyway.

**Comment by asamuzaK** [comment]
How about leaving the link to superuser.com you mentioned above in #5

**Comment by MasterKia** [comment]
> * The extension does not support some context menu items.

How about telling the user _which menu items aren't supported_ so the user could decide that the trade-off is worth it or not?




> * There is no easy way to restore the native tab bar.

Isn't deleting the `userChrome.css` file an *easy way* though?
A user who is able to correctly follow that instruction should also be able to delete that file just in case something happens.



> * If someone is aware of those above

How could they be? Actually I wasn't aware that some context menus aren't supported.
But I was indeed aware that if I want to restore native tabs I could just delete the `userChrome.css` file.

> * I am sure that they will search and find a solution themselves. Just like you did this time:-)

Agreed. I think having the tried and true instruction at hand in this repo isn't a bad idea either.



> How about leaving the link to superuser.com you mentioned above in #5

Sounds good to me. But the instructions in that superuser link are a bit scattered across the place (for example the steps to enable the custom css aren't mentioned in the first top answer so user might get confused). So I suggest having the "instruction from this PR + superuser link" in #5.

**Comment by asamuzaK** [comment]
> Isn't deleting the userChrome.css file an easy way though?

For light users who copy and use userChrome.css as is without considering the side effects, deleting userChrome.css is not an easy way, IMO.

> I suggest having the "instruction from this PR + superuser link" in https://github.com/asamuzaK/sidebarTabs/issues/5.

Fine with me. Please go ahead with that.

**Comment by MasterKia** [comment]
> Fine with me. Please go ahead with that.

Done, you could pin that issue so it's more visible to the users.

**Pull request closed without merging**
